"""add_anti_farm_time_limits

Revision ID: 67286289fe43
Revises: 5b2e83cd9f1a
Create Date: 2026-06-29 23:09:21.567544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67286289fe43'
down_revision: Union[str, Sequence[str], None] = '5b2e83cd9f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_members')
    op.add_column('rooms', sa.Column('valid_from_time', sa.Time(), nullable=True))
    op.add_column('rooms', sa.Column('valid_until_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'valid_until_time')
    op.drop_column('rooms', 'valid_from_time')
    op.create_table('room_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sa_orm_sentinel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_members'))
    )
    # ### end Alembic commands ###
